"""add original dates to project

Revision ID: 4c41071b4bca
Revises: 79897add14d5
Create Date: 2026-04-22 14:10:28.457962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c41071b4bca'
down_revision: Union[str, Sequence[str], None] = '79897add14d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('original_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('original_end_date')
        batch_op.drop_column('original_start_date')

    # ### end Alembic commands ###
