"""add project detail fields

Revision ID: 79897add14d5
Revises: d4a7e9c21f50
Create Date: 2026-04-21 14:24:55.609366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79897add14d5'
down_revision: Union[str, Sequence[str], None] = 'd4a7e9c21f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('division', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('announcement_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('submission_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bidding_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('evaluation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participation_limit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('joint_performance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subcontract_allowed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('win_amount', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('consortium_members', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('evaluation_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tech_score_ratio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_score_ratio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evaluation_agency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('negotiation_threshold', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deliverables', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pm_requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('language_requirements', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('special_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('announcement_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('announcement_url')
        batch_op.drop_column('special_notes')
        batch_op.drop_column('language_requirements')
        batch_op.drop_column('pm_requirements')
        batch_op.drop_column('deliverables')
        batch_op.drop_column('overview')
        batch_op.drop_column('negotiation_threshold')
        batch_op.drop_column('evaluation_agency')
        batch_op.drop_column('price_score_ratio')
        batch_op.drop_column('tech_score_ratio')
        batch_op.drop_column('evaluation_method')
        batch_op.drop_column('consortium_members')
        batch_op.drop_column('win_amount')
        batch_op.drop_column('subcontract_allowed')
        batch_op.drop_column('joint_performance')
        batch_op.drop_column('participation_limit')
        batch_op.drop_column('contract_method')
        batch_op.drop_column('evaluation_date')
        batch_op.drop_column('bidding_deadline')
        batch_op.drop_column('submission_deadline')
        batch_op.drop_column('announcement_date')
        batch_op.drop_column('division')
        batch_op.drop_column('project_type')
        batch_op.drop_column('announcement_number')

    # ### end Alembic commands ###
