"""add project pipeline fields

Revision ID: c14ad7746953
Revises: 858fa866ba87
Create Date: 2026-04-20 15:19:48.546700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14ad7746953'
down_revision: Union[str, Sequence[str], None] = '858fa866ba87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('bid_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_stage', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('proposal_writer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('proposal_writer')
        batch_op.drop_column('country')
        batch_op.drop_column('pipeline_stage')
        batch_op.drop_column('bid_deadline')
        batch_op.drop_column('budget')
        batch_op.drop_column('client')

    # ### end Alembic commands ###
